### ISSUE TITLE
Create a route to fetch Chapter names and Abbreviations from Strapi

### ISSUE THREAD

**Issue by shooboxx** [PBS-State-of-The-Bahamas/state-website#80]
**Backstory**
Currently, the nav bar hardcodes the chapters in the sub navigation which does not help to make navigation dynamic or provides future proof-ness.

**Issues**
1. There's a reliance on those pages actually existing. 
2. If those pages does not exist, it will go to a 404 page (even though the page clearly exists to a user)
3. If a chapter is removed/added in the future, the page does not go away

**Solution**
- Create a route that returns an array of chapter names and abbrevations

**Example** 
```
const chapterAbbreviations:  [
  {
    name: "Beta Beta Lambda",
    shortName: "BBL"
  },
  {
    name: "Delta Epsilon Sigma,
    shortName: "DES"
  },
  ...
]
```

**Comment by Stanico-Knowles** [comment]
Did you try /api/chapters?

**Comment by Stanico-Knowles** [comment]
For efficiency, /api/chapters?fields[0]=name&fields[1]=chapter_abbreviation
