### ISSUE TITLE
Chapter Homepage

### ISSUE THREAD

**Issue by quincyarthur** [PBS-State-of-The-Bahamas/state-website#9]
- [x] Create Hero Section Component 
- [x] Create Chapter History Component
- [x] Implement Charter Member Component
- [x] Create Chapter Awards Component
- [x] Create Gallery Grid Component
- [x] Interest Contact Form Component
- [x] Wire Up Contact Form to Strapi Email Client

**Comment by QARTHUR-NIB** [comment]
PR should be ready on Wednesday March 8th, 2023
